### ISSUE TITLE
Mejor uso de "issues"

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#11]
Espero que cada tarea sea resuelta como un documento independiente (**no como un comentario a un issue**) y que lo agregues al repositorio como un elemento de *code* con una acción de "commit", lo que te dará un número de control que puedes usar para vincularlo a un comentario apropiado en el asunto en cuestión. Del mismo modo que hice yo con el documento [primeros pasos](f729c9a).

Sugiero que marques los _issues_ con **labels** (hay unas cuantas ya creadas y puedes crear más con el botón que está al lado del filtro en el encabezado de **issues** Lo mismo va con las **milestones** o **hitos**, que son resultados notables como productos terminados (asociados a una fecha de entrega). No hay ninguno precargado pero hay un botón al lado de labels para hacerlo.

Luego puedes asignar **etiquetas**, **hitos** e incluso tu *nombre* o el mío como **asignatarios** para anotar _issues_ específicos, previamente seleccionados mediante la marca de selección que tiene cada uno a la izquierda.

Esto será importante y útil para mejorar el control y seguimiento de las tareas que van a ir surgiendo.

Por cierto, nota que también puedes "priorizar" las actividades simplemente arrastrandolas a distintas posiciones en la lista, digamos que las más importantes siempre están arriba en la lista!!!!!

**Comment by Amaureto** [comment]
No había visto este issue. Ya agregué la primera tarea como archivo .md

**Comment by equihuam** [comment]
Faltaría ensayar el uso de etiquetas e hitos para dar por concluido este asunto. Te sugiero además hacer un uso amplio de estas dos cosas.

**Comment by equihuam** [comment]
La forma de calendarizar es con la creación de **Milestones** y los nombres que elegiste están casi bien para esos fines. Yo diría que los podrías convertir a  algo así como **Markdown tarea 1**, generalos del mismo modo que hiciste con las **Labels** pero ahora con el botón **Milestone**. Piensa que las Labels señalan el tipo de asunto y los hitos el resultado final esperado y la fecha en la que se entregará.  Veras un calendario a la derecha en la pantalla de creación de **Milestones** para ese propósito.

**Comment by equihuam** [comment]
Hecho. Veo que ya tienes entendido el tema de etiquetar y fijar metas. Sólo resta que las uses efectivamente, pero para los propósitos de aprendizaje considero que está entendido el asunto. Bajo esta premisa los doy por concluida esta tarea y la cerraré.
