### ISSUE TITLE
Compartir acceso

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#21]
Para poder hacer uso de varias funciones de GitHub necesitas indicar quienes son los colaboradores aceptados. Todo el mundo puede ver el repositorio hasta ahora, pero sólo los miembros de grupo y el propietario pueden interactuar más estrechamente y modificar el contenido del almacén. 

Para hacer esto tienes que ir a **Settings**, en el renglón abajo del título del repositorio y hasta la derecha. Lo seleccionas y aparecerá una lista de especificaciones de trabajo. Entra a la de [Collaborators](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) y anota los nombres de usuario que quieras invitar (deberán aceptar la invitación que reciban):

- equihuam
- maqueo
- jequihua

son algunos candidatos que puedes querer incluir.

**Comment by Amaureto** [comment]
Listo! Ya envié las invitaciones.

**Comment by equihuam** [comment]
Bien hecho!!!!
