### ISSUE TITLE
Dudas-Repaso

### ISSUE THREAD

**Issue by Amaureto** [Amaureto/Ecoacustics_MX#26]
@equihuam Estuve repasando lo aprendido hasta el momento y colocaré en este issue algunas dudas:

La primera 1) ¿A qué se debe que el directorio de archivos que veo en Jupyter notebook (que abre los que tengo guardados en mi máquina) no es el mismo que veo en GitHub? ¿Tengo que cargar los archivos al repositorio con la opción UPLOAD? O estoy haciendo algo mal con GitSinc?

![Jupyter Notebook](https://cloud.githubusercontent.com/assets/17288698/22949479/0d2f0ffc-f2c8-11e6-830e-65de2777c126.png)

![Repositorio GitHub](https://cloud.githubusercontent.com/assets/17288698/22949225/2212f39e-f2c7-11e6-8d79-12c84232e8ac.png)

**Comment by equihuam** [comment]
Lo que pasa es que GIT sólo lleva control de lo que le digas (mediante el +
en tortoisegit). En cambio en el directorio de tu equipo están archivos
controlados en versiones y también los no controlados. En realidad no
conviene controlar todo. Por ejemplo temporales o datos que pueden ser
archivos grandes que no cambiarán, etc. En resumen, tú decides que quieres
poner en el sistema de seguimiento a los cambios.

**Comment by Amaureto** [comment]
Utilicé la opción *Tortoise-add* para cargar las versiones más recientes que ya tenía pero no se habián actualizado en el repositorio.  Hice *commit* y *push* con éxito. Por favor indícame si ves los cambios. Los archivos de las cuatro tareas terminadas inician con la nomenclatura "TA1, ..., TA4"

**Comment by equihuam** [comment]
Sólo es necesario dar "add" cuando un archivo es nuevo para el sistema e control de versiones. Una vez que lo tienes controlado GIT no lo oliva. Puede incluso ocurrir que determines cambiarle el nombre a un archivo controlado. En tal caso sí deberas darle add para registrar el nuevo nombre, pero GIT se dará cuenta por si mismo de que ese archivo ya tiene historia registrada. Muy chido!!!!
