### ISSUE TITLE
Calendario de actividades

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#5]
Hola Amauri,

Ahora lo que seguiría es que propongas un programita de trabajo para abordar las sugerencias que te he hecho. Esto debería incluir actividades del avance del proyecto. Sale?

M

**Comment by Amaureto** [comment]
Hola Miguel, estuve revisando el archivo de *primeros pasos* y me está costando bastante trabajo entender. Por ahora propongo el siguiente
##**CALENDARIO DE ACTIVIDADES**
#Viernes 27 al Lunes 30-ene-2017
Instalación y exploración de Anaconda y Jupiter, familiarizarme con la sintaxis de Markdown.
#Martes 31-ene-2017
Explorar folium con python
#Miércoles 1-feb-2017
Explorar el uso de R Markdown en RStudio
#Jueves 2 y viernes 3-feb-2017
Explorar la graficación en ggplot2 con R y matplotlib con python
#Lunes 6-feb-2017
Envío de manuscrito de tesis actualizado al Comité Tutorial

No se qué te parezca. 
P.D. El editor Sublime text es de paga?
Saludos,

**Comment by equihuam** [comment]
# Calendario de Actividades

| Inicia     | Entrega | Resultado|
|:-----------|:---------|:----------:|
|27-ene     | 30-ene| Anaconda y Jupiter instalados y elaboración de un texto con la sintaxis de Markdown con encabezados, 5 nombres científicos italizados en un cuadro y la ecuación del índice de Shannon|
|31-ene     | |  Mapa con marcadores de unas 10 observaciones en distintos sitios alrededor de Xalapa, de alguna especie de rana|
|1-feb        | |Documento elaborado con R Markdown con el resumen estadístico de la precipitación del último año en Xalapa y una gráfica sobre su comportamiento mensual|
|2-feb        |3-feb| Graficación con ggplot2 en R de la longitud media de 10 especies de ranas con puntos que varién por color según su  coloración dominante el tamaño del punto varié según el peso promedio de la especie. Similar gráfica hecha con matplotlib en python|
|6-feb        | |Manuscrito de tesis actualizado recibido por el Comité Tutorial|

**Comment by equihuam** [comment]
Si este ejercicio de definición de actividades queda suficientemente claro propongo dar por concluido el asunto "calendario de actividades" y Abrir una serie de nuevos "asuntos", uno por cada una de las tareas pactadas, para así poderles dar seguimiento puntual a cada una por su lado. ¿De acuerdo?

**Comment by equihuam** [comment]
Sublime tiene un precio, pero lo puedes usar cuanto quieras antes de pagar.

**Comment by Amaureto** [comment]
### **Anfibios anuros de la región montañosa del Centro de Veracruz**


#Cuadro con 5 especies 
| Familia   | Especie | Nombre común| Abundancia|
|:-----------|:---------|:----------|:----------|
|Bufonidae    |*Incilius cristatus* |Sapo de cresta|
|Centrolenidae |*Hyalinobatrachium fleischmanni* |Rana de cristal |
|Craugastoridae   |*Craugastor rhodopis* |Rana de hojarasca |
|Hylidae    |*Charadrahyla taeniopus* |Rana de árbol jarocha |
|Hylidae    |*Ecnomiohyla miotympanum* |Rana de árbol orejas chicas |
|Hylidae     |*Plectrohyla arborescandens* |Rana menor de bromelia |

**Comment by equihuam** [comment]
OK. En la anotación de encabezados" es necesario dejar un espacio entre el marcador y el texto. A vece ocurre también que hay que dejar líneas en blanco entre segmentos de marcado distintos. Agrega solamente unl espacio entre el "#" y "Cuadro" y ve el resultado.  Falta el italizado y la ecuación!!!!. En la parte de arriba del editor hay un acceso rápido a énfasis (tamaño del texto), negrillas e itálicas. Prueba a usarlo. Qué más se puede hacer con esa paleta de ayuda? Probaste a usar la pestaña de "Preview" para ver el resultado de tu edición?
