### ISSUE TITLE
Primer texto con Markdown

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#6]
Anaconda y Jupiter instalados y elaboración de un texto con la sintaxis de Markdown con encabezados, 5 nombres científicos italizados en un cuadro y la ecuación del índice de Shannon.

**Comment by equihuam** [comment]
OK, vi tu solución parcial en el "issue" sobre calendario que ya cerraste. Te sugería que hicieras un "issue" por cada tarea, así que ya te adeltante en eso. Espera a cerrar cada punto hasta que estemos los dos satisfechos con el resultado.
 
En la anotación de encabezados" es necesario dejar un espacio entre el marcador y el texto. A vece ocurre también que hay que dejar líneas en blanco entre segmentos de marcado distintos. Agrega solamente unl espacio entre el "#" y "Cuadro" y ve el resultado. Falta el italizado y la ecuación!!!!. En la parte de arriba del editor hay un acceso rápido a énfasis (tamaño del texto), negrillas e itálicas. Prueba a usarlo. Qué más se puede hacer con esa paleta de ayuda? Probaste a usar la pestaña de "Preview" para ver el resultado de tu edición?

**Comment by Amaureto** [comment]
Elaboración de un texto con la sintaxis de Markdown con encabezados, 5 nombres científicos italizados en un cuadro y la ecuación del índice de Shannon. Fecha de entrega: 30/enero/2017

# Anfibios anuros útiles para monitoreo acústico en los alrededores de Xalapa

## Introducción

Los anfibios son considerados como organismos bioindicadores del estado de un ecosistema dada su sensibilidad ante los cambios ambientales. Una de las zonas con mayor riqueza de anfibios de México y con un importante número de endemismos es la región montañosa central del estado de Veracruz (RMCV), ubicada en los límites septentrionales del Neotrópico ([Ochoa-Ochoa y Flores-Villela 2006](https://books.google.com.mx/books?hl=es&lr=&id=1zib6ltYfIUC&oi=fnd&pg=PA1&dq=%C3%81reas+de+diversidad+y+endemismo+de+la+herpetofauna+mexicana.&ots=lD7kZAf1si&sig=QdOOKjWBMWG7TgL0ViX7v8RzTr8#v=onepage&q=%C3%81reas%20de%20diversidad%20y%20endemismo%20de%20la%20herpetofauna%20mexicana.&f=false)); además en esta zona, se concentran algunas de las especies micro-endémicas más amenazadas (Ochoa-Ochoa et al 2009; Ochoa-Ochoa et al. 2011). En esta región, el bosque de niebla, como vegetación nativa predominante, se ha reducido en extensión quedando remanentes aislados con diferente grado de perturbación y se ha transformado en distintos sistemas agrícolas entre los que figuran: cafetales, pastizales para ganado y cultivos de caña de azúcar, así como asentamientos humanos (Castillo-Campos et al. 2011). Los anuros (ranas y sapos) son productores prodigiosos de sonidos, de hecho, sus vocalizaciones son consideradas su modo primario de comunicación (Wells 1977; [Gerhardt, 1994](http://www.annualreviews.org/doi/pdf/10.1146/annurev.es.25.110194.001453)). El sonido producido por los animales (biofonía) es un componente importante de la mayoría de los ecosistemas y por lo tanto, el monitoreo de los anfibios anuros que vocalizan en la zona puede ser de utilidad para evaluar de una forma no intrusiva la condición de los bosques de niebla de la región.

## Objetivos
Identificar las especies de anfibios que vocalizan más características del bosque de niebla de la región montañosa del centro de Veracruz.

## Métodos 
El trabajo de campo se llevó a cabo en los alrededores de Xalapa, dentro de la región montañosa central del estado de Veracruz. La búsqueda de anuros se ejecutó principalmente en fragmentos de bosque de niebla, pero también se visitaron áreas circundantes a los mismos, especialmente con cuerpos de agua (ríos, arroyos o charcas temporales). Se consideraron únicamente los registros auditivos, es decir, aquellos individuos vocalizando.

## Resultados
Se registraron 268 individuos pertenecientes a nueve especies de anuros. En el siguiente cuadro se muestran las cinco especies de anfibios anuros que se encontraron vocalizando con mayor frecuencia en los bosques de niebla de la región.

### Cuadro

| Familia   | Especie | Nombre común|Abundancia|
|:-----------|:---------|:----------|:-------:|
|Centrolenidae |*Hyalinobatrachium fleischmanni* | Ranita de cristal | 59 | 
|Craugastoridae   |*Craugastor rhodopis* |Rana de hojarasca | 12 | 
|Eleutherodactylidae |*Eleutherodactylus cystignathoides* | Ranita chirriadora del río Grande | 32 | 
|Hylidae    |*Ecnomiohyla miotympanum* |Rana de árbol orejas chicas | 130 | 
|Hylidae     |*Plectrohyla arborescandens* |Rana menor de bromelia | 28 | 

### Fórmula del Índice de Shannon (H´)

$$
  H = - \sum_{i=1}^{i=S} p_i \cdot log_2 (p_i)
$$
Para el ensamble de anuros registrados se obtuvo un valor de H´= -1.44

# Observaciones
@equihuam estos son mis comentarios de la actividad:

1.  No encontré como editar un lenguaje de notación matemática, 
> Copié la fórmula de otro [repositorio](https://github.com/jumanbar/Curso-R/blob/master/ejercicios-de-programacion/rep-1-src/INSTRUCCIONES.md)

2.  Si utilizé la paleta de ayuda y la opción preview

3. Me registré e instalé en la computadora de trabajo tanto **[Anaconda](https://anaconda.org/amaureto/)** como **Jupyter Notebook**.

**Comment by equihuam** [comment]
Excelente resultado Amauri. Lo resolviste muy bien. 

Efectivamente la versión de markdown de Github no tiene resuelto el despliegue de fórmulas, pero la que escribiste se despliega perfecto. La puedes ver en Sublime si lo instalaste (aunque tendrás que instalar [algunas adiciones](http://plaintext-productivity.net/2-04-how-to-set-up-sublime-text-for-markdown-editing.html) para uso y despliegue de textos markdown).  Otra opción para verlo en todo su esplendor es cambiarle la extensión de "md" a "rmd" para entonces abrirlo en RStudio y pedirle que lo _teja_ para **html** o para **MSWord** (que es lo más fácil, para hacerlo en pdf necesitarías instalar más cosas). Ojalá te guste el resultado. 

Con lo que lograste estoy de acuerdo en dar por concluido este asunto y que cerremos el [issue #6](#6)

**Comment by equihuam** [comment]
Bueno, como no te decides a cerrarlo yo lo daré por concluido y lo cerraré.
