### ISSUE TITLE
TA2. Primer mapa con Python y folium

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#7]
Mapa con marcadores de unas 10 observaciones en distintos sitios alrededor de Xalapa, de alguna especie de rana

**Comment by Amaureto** [comment]
Miguel @equihuam. No pude hacer el mapa usando phyton, no se si al instalar hice algo mal pero la ventana del Jupyter notebook se cierra sola. No entiendo mucho donde colocar las instrucciones a pesar de que ya revisé el [readme](https://github.com/python-visualization/folium/blob/master/README.rst) y también el [ejemplo](https://blog.dominodatalab.com/creating-interactive-crime-maps-with-folium/)

Según yo son estas las instrucciones para crear el mapa pero no se dónde colocarlas:

### Mapa con 10 observaciones de la rana Plectrohyla arborescandens

$ pip install folium
import folium
P_arb_map = folium.Map(location=[19.4, -97.03] zoom_start=12, tiles='Stamen Terrain')
folium.Marker([19.46106, -97.046611], popup='01', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.46075, -97.047222], popup='02', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45931	-97.046611], popup='03', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.49089,	-97.031083], popup='04', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45964,	-97.045556], popup='05', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45653,	-97.046222], popup='06', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45708,	-97.046139], popup='07', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45653,	-97.046278], popup='08', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45650,	-97.046083], popup='09', icon = folium.Icon(color ='green')).add_to(P_arb_map)
folium.Marker([19.45658,	-97.046222], popup='10', icon = folium.Icon(color ='green')).add_to(P_arb_map)
P_arb_map.save('parb10rec.html')('arborescandens10rec.html')

![captura de pantalla 2017-01-31 21 39 47](https://cloud.githubusercontent.com/assets/17288698/22494517/bea483f0-e7fd-11e6-83b2-9ef34725259e.png)

**Comment by equihuam** [comment]
Debes tener dos archivos ejecutables de **Jupyter**: _Notebook_ y _QtConsole_, el que necesitas es el primero. Cuando lo ejecutes se aabrira una ventana de comandos negra que ejecutará cosas y desplegará textos. Si algo sale mal esos textos describiran el problema (toma nota de lo que va saliendo). Si todo sale bien entonces se abrira encima una página del navegador que ahora se convierte en una ventana a tu "Notebook" de python en este caso y es ahí en donde deberas operar los comandos de python.

Debes ver inicialmente una página así:

![image](https://cloud.githubusercontent.com/assets/3107876/22497028/218fad4e-e814-11e6-8246-bc3708ed47ad.png)

A la derecha hay un botón _New_ que debes apretar para crear un Notebook Python. Al hacerlo debe aparecer algo así:

![image](https://cloud.githubusercontent.com/assets/3107876/22497203/7f682eea-e815-11e6-8de8-0b7527ddd3e3.png)

Es aquí en donde deberás poner tu código.

En una primera celda escribe esto para instalar el paquete con la biblioteca.

`!pip install folium`

Una vez escrito, aprieta el botón **run cell**  que tiene una flechita junto con una barrita. Debe reportarte que se instaló folium y ahora estás listo para empezar a escribir tu escript en python. Nota que esto no es Python todavía, es un procedimiento de instalación previo y en el caso de Jupyter es necesario usar el símbolo "!" para indicar que es un comando para el sistema de archivos. Con la mísma lógica podrías poner `!dir` y obtendrías una lista de archivos en el directorio de trabajo.

Te sugiero pongas lo siguiente en otra celda, antes de sufrir con tus meros datos. Cualquier línea que inicies con "#" no es ejecutada, es un comentario o explicación de lo que hace (o esperas haga) el código que le sigue.

```
# Carga y prepara la biblioteca
import folium 

# Crea un objeto de tipo "mapa" para la ventana centrada en las coordenadas indicadas.
P_arb_map = folium.Map(location=[19.4, -97.03], zoom_start=12, tiles='Stamen Terrain')

# Despliega el objeto "mapa" que creaste.
P_arb_map
```

Ojalá llegues facilmente hasta aquí. Otra posibilidad es hacerlo con Anaconda. Busca una cosa que se llama Spyder, que te dará un ambiente de programación que puedes usar para lo mismo.

Cuando tengas tu tarea completa puedes usar el botón "Download as" (Python) para guardar el escript en donde quieras y ese será el archivo que deberas subir al repositorio. Mientras tanto puedes darle Save, lo que hace guarda tu trabajo en la nube

Por cierto, **pip** es un _agente simplificado de instalación_. Sí Anaconda está bien instalado, lo puedes
usar desde una ventana de comando en cualquier lado. Para hacerlo puedes escribir `cmd` en la ventana de inicio de Windows o desde el explorador de archivos puedes escoger algún directorio (no importa mucho cual) y en el menú "archivo" elegir la opción "Abrir símbolo de sistema". En la ventana negra que aparecerá puedes escribir pip install <paquete que quieras> y eso instalará el paquete indicado para siempre en tu máquina.

**Comment by Amaureto** [comment]
Hola Miguel, muchas gracias. El problema es que la ventana negra de Phyton Notebook se cierra rápidamente y no aparece ninguna ventana del navegador como la que me muestras.

**Comment by equihuam** [comment]
Entonces sí hay un problema de instalación. Intenta Anaconda y spyder
entonces

El 1 feb. 2017 14:34, "Amaureto" <notifications@github.com> escribió:

Hola Miguel, muchas gracias. El problema es que la ventana negra de Phyton
Notebook se cierra rápidamente y no aparece ninguna ventana del navegador
como la que me muestras.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Amaureto/Ecoacustics_MX/issues/7#issuecomment-276773806>,
or mute the thread

**Comment by equihuam** [comment]
Para averiguar un poco más que puede estar pasando con Jupyter te sugiero lo siguiente:

1. Abre una ventana de comando (teclear **cmd** en la ventana _inicio_ de Windows o en el "buscador" de windows 10 o usar el menú "archivo" desde el explorador de archivos y elegir _Abrir símblo de sistema_.
2. En la ventada de comandos del sistema escribe: 
  `python --version`
  deberá desplegar untexto del estilo **Python 3.5.2 :: Anaconda 4.1.1 (64-bit)**. Esto demostrará que python está disponible y localizable automáticamente como debe ser. Si no es así hay que [anotar la ubicación de la instalación de Anaconda en la variable "path" del sistema](http://gatomontez.com/articulo/2014/02/16/computo-cientifico-con-python-y-anaconda/#.WJKiDvnhBEY) y esta es una [receta]8http://superuser.com/questions/143119/how-to-add-python-to-the-windows-path) directa. Verificar nuevamente que el comando de arriba funcione.
4. Una vez que python esté respondiendo entonces puedes usarlo para correr escripts como los siguientes y escribe en un solo renglón:
  `C:\Anaconda3\python.exe C:\Anaconda3\cwp.py C:\Anaconda3 "C:/Anaconda3/python.exe" "C:/Anaconda3/Scripts/jupyter-notebook-script.py"`
  substituye la parte "C:\Anaconda3" por la que aplique a tu equipo para localizar "Python.exe". Ten cuidado con el tipo de diagonal que uses, debe corresponder con las que están anotadas y mantén las comillas en dónde están. Esto debe lanzar el acceso a Jupyter en el **Browser** y aunque fallara no debería cerrarse, así que deberás poder seguir el éxito o fracaso de los pasos de activación. En caso de que falle copia el texto y pegalo aquí para que lo discutamos. Para hacerlo simplemente tienes que marcarlo con el mouse y apretar "return", eso copiará lo seleccionado al "clip".

**Comment by Amaureto** [comment]
Muchas gracias por las instrucciones. Hoy sufrí bastante de cefalea y cervicalgia. Mañana me actualizo. Saludos.

**Comment by Amaureto** [comment]
Sí estaba bien instalado. Lo que hice fue abrir el *cmd* y escribir *jupyter notebook*, en lugar de abrir el ícono de "Jupyter Notebook" que aparece en mi barra de inicio. Posteriormente instalé y actualicé la versión del paquete folium usando la ventana del navegador. 
![captura de pantalla 2017-02-03 01 08 34](https://cloud.githubusercontent.com/assets/17288698/22582641/9e28d0c0-e9ad-11e6-9dca-8747bbaebf9f.png)

**Comment by equihuam** [comment]
Veo que tienes las tareas en distintas ramas. Te sugiero las lleves a la rama principal con un **merge to master**

**Comment by Amaureto** [comment]
Tarea terminada. Una forma rápida de hacer mapas interactivos.

**Comment by equihuam** [comment]
Es cierto que está listo, pero me quiero asegurar de que viste los comentarios que están en el archiov con terminación "py" y que puedes abrir con Spyder. Por favor velo.

**Comment by Amaureto** [comment]
Sí vi tus comentarios
-Omití las celdas vacías (sin instrucciones)
-No entendí el uso de las tres comillas para crear un bloque, lo hice pero no vi cambios.
-Omití el comando innecesario de instalar folium
-Cuando le doy descargar al archivo se nombra incluyendo varios "+" y al abrirlo en Spyder muestra el siguiente error: 
![image](https://cloud.githubusercontent.com/assets/17288698/22992350/16398682-f385-11e6-8fb9-7ed1b60af767.png)

**Comment by equihuam** [comment]
No notas el efecto de las comillas pues las pusiste después del #. La ideas
es que con las tres comillas el bloque ya no necesita los gatos.

No te reportó ningún error, aunque este en rojo. La palabra error no
aparece pie ningún lado. Lo que ocurrió es que el programa hizo su cosa y
no lo notaste. Debes Tener el archivo que le pediste guardar en el disco y
misión cumplida bye!

Precisamente eso es lo que quería que notarás. En el enfoque Jupyter estas
escribiendo algo que incluye código. Aquí lo único que interesa es un
algoritmo que resuelva con eficiencia una tarea.

**Comment by Amaureto** [comment]
Efectivamente, el mapa se guardó en mi directorio. Gracias. 

![captura de pantalla 2017-02-22 11 56 35](https://cloud.githubusercontent.com/assets/17288698/23225016/12ee5bc6-f8f6-11e6-9e91-599ce9c6503a.png)
