### ISSUE TITLE
Primer documento R Markdown

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#8]
Documento elaborado con R Markdown con el resumen estadístico de la precipitación del último año en Xalapa y una gráfica sobre su comportamiento mensual

**Comment by Amaureto** [comment]
Ya subí este documento en formato .Rmd

Tengo una duda, entiendo que de estas dos opciones:
- [  ] Commit directly to the master branch.
- [x ] Create a new branch for this commit and start a pull request. Learn more about pull requests.

debo seleccionar la segunda para solicitar mediante *pull request* que tu revises el documento y si no hay cambios yo lo añado a la *master branch*.

**Comment by equihuam** [comment]
Dado que tu eres el dueño de este repositorio en ti recae la responsabilidad de juzgar que es ceptable para ingresar al historial de actividades que contribuyan al desarrollo de los productos. Por lo tanto lo que tu hagas debe ir como un **commit directly to the master branch**. Si solicitaras un "pull", te lo harías a ti mismo!!!! Yo no lo puedo hacer directamente, porque no soy el responsable del repositorio, así que tengo que solicitar que tu juzgues lo que te propongo añadir a él. 

En caso de que estes haciendo algo de consideres no es de interés directo para lo que estas desarrollando, lo que tendrías que hacer es crear una nueva rama para darle seguimiento a ese experimento, sin contaminar la historia principal del producto, en caso de que resulte buena la idea entonces harpia un merge con la rama "master". En nuestro caso, no es muy probable que esto ocurra pues precisamente lo que queremos es tener la conversación completa en primer plano. 

Yo uso estas ramas por ejemplo, para acomodar cambios a una presentación que usaré para distintos foros, así que hago una rama para cada uno de ellos y mantengo la original en la "master".

**Comment by equihuam** [comment]
Ya pude ver lo que propones y ajuste un poquitín el texto y te anoté algunas ideas de como mejorar el código para hacerlo más operativo. 

Dos cosas generales. 

1) El uso de _usuario_@ es una opción de Github, no funciona en RMarkdown (tampoco tiene mucho sentido, pues no hay realmente un registro de usuarios en operación aquí). 
2) El documento está bien, pero sería más interesante si lo tratas como un pequeño reporte y explicas más sobre los datos y los resultados.

**Comment by Amaureto** [comment]
Tarea terminada. Sólo me falta conocer más la ayuda de [Markdown Quick Reference](https://en.support.wordpress.com/markdown-quick-reference/)

**Comment by equihuam** [comment]
Muy bien Amauri. Listo para cerrar. 
Sólo noté el detalle de que copias el dato de precipitación del *data.frame* a una variable *PRECIPITACION*. Esto es útil para simplificar la legebilidad del código pero no realmente necesario. Simplemente para que lo tengas presente. Noto que estas haciendo algo semejante en Python y también aplica esta misma idea.
Actualiza el repositorio con mi "pull request" y listo. Puedes cerrar el asunto

**Comment by equihuam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prueba](https://trello.com/c/ScVjPh66/66-prueba)

**Comment by Amaureto** [comment]
De acuerdo.
