### ISSUE TITLE
TA4. Primera gráfica con ggplot2 en R y con Matplotlib en python

### ISSUE THREAD

**Issue by equihuam** [Amaureto/Ecoacustics_MX#9]
Graficación con ggplot2 en R de la longitud media de 10 especies de ranas con puntos que varién por color según su coloración dominante el tamaño del punto varié según el peso promedio de la especie. Similar gráfica hecha con matplotlib en python

**Comment by Amaureto** [comment]
Sólo para aclarar si entendí la instrucción: ¿Requiero datos de longitud, peso y coloración para 10 especies de ranas? Luego graficaré la longitud media (variable Y) y los marcadores de estos datos variarán por color según la coloración dominante de la rana y por tamaño según el peso promedio. 
Mi duda es si ¿la variable color debo transformarla a tipo numérico? (por ejemplo usando un valor arbitrario según considere o la escala de valores de color RGB). 
Adjunto los datos que usaré.
![image](https://cloud.githubusercontent.com/assets/17288698/22583690/da5c16aa-e9b3-11e6-8c34-8f5bf03252cd.png)

**Comment by equihuam** [comment]
La idea es que el punto tenga color. Eso puede asociarse con números
directamente o categorías de color en una variable de tipo factor.

**Comment by Amaureto** [comment]
Sigue pendiente terminar la gráfica en matplotlib. No encuentro cómo indicarle que grafique una variable categórica (Especie) con una continua (longitud promedio) y que además los puntos varién en color de acuerdo a su coloración y en tamaño de acuerdo al peso. Se me hizo más fácil usando ggplot2 en R.

**Comment by equihuam** [comment]
En vista de que te atoraste mucho con Matplotlib te pongo una solución casi completa. Estudiala y termina el notebook en Jupyter, Podrías también tratar de hacerlo funcionar en Spyder. Te dejé notas de algunos toques finales que te pido hagas. El truco que yo use para darle vuelta al tema de las categorías fue generar una variable numérica con la función [range](http://pythoncentral.io/pythons-range-function-explained/) de python, que genera una secuencia entre 0 y un valor especificado, en este caso la longitud de la serie de datos. Asegurate de comprender todos los elementos del código.

**Comment by equihuam** [comment]
Para ver lo que te sugieron deberás aceptar mi solicitud de incorporar mi nueva versión del código (**pull request**)

**Comment by equihuam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MatplotLib](https://trello.com/c/ScVjPh66/66-matplotlib)

**Comment by equihuam** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MatplotLib](https://trello.com/c/ScVjPh66/66-matplotlib)

**Comment by Amaureto** [comment]
Ya hice el *Git-commit* de la carpeta de esta tarea y puse comentarios ahí. Básicamente actualicé los archivos de las tareas y de los datos (tenía mal las unidades en la variable longitud). 
ToDo: 
1)No entiendo muy bien todavía cuándo debo y cuándo no hacer el *pull* y el *push*. 
2)Me falta explorar y practicar esto mismo en [**Spyder**](http://pythonhosted.org/spyder/).
3)Noté que en el archivo **RMarkdown**, el gráfico generado con *ggplot2* no muestra el marcador para una de las especies. No encontré el error.

**Comment by equihuam** [comment]
1) Debes hacer *commit* con frecuencia. Cada vez que quieras actualizar con lo que está pasando en el repositorio debes dar un *pull*. Como en este caso tu tienes control completo de los cambios en tu *repositorio remote*, pues tu sabes cuando cambia!!!!!! Así que a lo mejor te puedes ahorrar algunos **pulls**. Siempre que quieras compartir tu avance con los demas (o sea yo!!!) debes dar un *push*,de otro modo nadie se enterará de lo que has hecho, más que tú!
2) Spyder debe estar muy fácil de hacer, pidele a Jupyter que te de un *download* en formato **Python (py)** y luego abres ese archivo en Spyder.
3) Típic sufrimiento. Solución, si no es un problema de *código*, entonces es un problema de datos. Es decir revisar primero la lógica de tu algoritmo y luego verificar que estes tratando los datos adecuadamente. En tu caso, tienes un espacio extra en el color Café, de modo que cuando crees que le estas dando una traducción a un color determinando para graficarlo resulta que tu código no encuentra la etiqueta que indicas por ningún lado y pero aún, la que si encuentra no tiene ninguna equivalencia, por lo tanto no tiene como representarla y le da un valor nulo. Yo creo que lo ideal en este caso es corregir la tabla de datos, a menos que la fuente de datos esté así y entoces quizás lo que conviene es actuar a nivel de la lógica del escript. De hecho es un error común y existen opciones precisamente para [eliminar espacios en blanco](http://stackoverflow.com/questions/2261079/how-to-trim-leading-and-trailing-whitespace-in-r) antes o despues de palabras o frases!!!!

**Comment by Amaureto** [comment]
1. Ya logré hacer el commit el push de las tareas terminadas y cargué al repositorio las versiones más recientes que tenía en mi máquina.
2. Ya descargué y leí el archivo py en **Spyder**. Usé las opciones "ejecutar archivo" y "ejecutar la celda actual". El menú de este programa me parece sencillo e intuitivo. Vi que las "terminales" de *Spyder* equivalen a las "consolas" de *R* y a las celdas "out" de *Jupyter*. 
![Spyder](https://cloud.githubusercontent.com/assets/17288698/22991342/8e67d11c-f381-11e6-947e-175d97db8d84.png)
3. Revisé el error de los espacios en blanco. 
¿Ya podemos dar por cerrado este issue?

**Comment by equihuam** [comment]
Bien hecho. Demosla por terminada!!!!!
